CLASS LHC_ZZCIR_CIT_DBT_CB60060 DEFINITION INHERITING FROM CL_ABAP_BEHAVIOR_HANDLER.
  PRIVATE SECTION.
    METHODS:
      GET_GLOBAL_AUTHORIZATIONS FOR GLOBAL AUTHORIZATION
        IMPORTING
           REQUEST requested_authorizations FOR ZzcirCitDbtCb60060
        RESULT result.
ENDCLASS.

CLASS LHC_ZZCIR_CIT_DBT_CB60060 IMPLEMENTATION.
  METHOD GET_GLOBAL_AUTHORIZATIONS.
  ENDMETHOD.
ENDCLASS.
